In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset_train = pd.read_csv('train.csv')

In [4]:
dataset_train.head()

Severity  Safety_Score  \
0                Minor_Damage_And_Injuries     49.223744   
1                Minor_Damage_And_Injuries     62.465753   
2        Significant_Damage_And_Fatalities     63.059361   
3  Significant_Damage_And_Serious_Injuries     48.082192   
4        Significant_Damage_And_Fatalities     26.484018   

   Days_Since_Inspection  Total_Safety_Complaints  Control_Metric  \
0                     14                       22       71.285324   
1                     10                       27       72.288058   
2                     13                       16       66.362808   
3                     11                        9       74.703737   
4                     13                       25       47.948952   

   Turbulence_In_gforces  Cabin_Temperature  Accident_Type_Code  \
0               0.272118              78.04                   2   
1               0.423939              84.54                   2   
2               0.322604              78.86                   7   
3               0.337029              81.79                   3   
4               0.541140              77.16                   3   

   Max_Elevation  Violations  Adverse_Weather_Metric  Accident_ID  
0    31335.47682           3                0.424352         7570  
1    26024.71106           2                0.352350        12128  
2    39269.05393           3                0.003364         2181  
3    42771.49920           1                0.211728         5946  
4    35509.22852           2                0.176883         9054

In [5]:
x = dataset_train.drop(['Severity'] , axis = 1)

In [6]:
y = dataset_train['Severity']

In [7]:
x = x.drop(['Accident_ID'], axis = 1)

In [8]:
x.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     49.223744                     14                       22   
1     62.465753                     10                       27   
2     63.059361                     13                       16   
3     48.082192                     11                        9   
4     26.484018                     13                       25   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       71.285324               0.272118              78.04   
1       72.288058               0.423939              84.54   
2       66.362808               0.322604              78.86   
3       74.703737               0.337029              81.79   
4       47.948952               0.541140              77.16   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  
0                   2    31335.47682           3                0.424352  
1                   2    26024.71106           2                0.352350  
2                   7    39269.05393           3                0.003364  
3                   3    42771.49920           1                0.211728  
4                   3    35509.22852           2                0.176883

In [9]:
y.head()

0                  Minor_Damage_And_Injuries
1                  Minor_Damage_And_Injuries
2          Significant_Damage_And_Fatalities
3    Significant_Damage_And_Serious_Injuries
4          Significant_Damage_And_Fatalities
Name: Severity, dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [11]:
y

array([1, 1, 2, ..., 3, 1, 0])

In [12]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size = 0.15 , random_state = 0 )

In [13]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test  = sc_x.transform(x_test)

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


In [14]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 10 , criterion = 'entropy')

In [15]:
model.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [16]:
y_pred = model.predict(x_test)

In [17]:
y_pred

array([0, 3, 0, ..., 3, 1, 3])

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
cm = accuracy_score(y_test , y_pred)

In [20]:
cm

0.8993333333333333

In [ ]:
d = {0 : 'Minor_Damage_And_Injuries' , }

In [21]:
y_pred = label_encoder.inverse_transform(y_pred)

In [22]:
y_pred

array(['Highly_Fatal_And_Damaging',
       'Significant_Damage_And_Serious_Injuries',
       'Highly_Fatal_And_Damaging', ...,
       'Significant_Damage_And_Serious_Injuries',
       'Minor_Damage_And_Injuries',
       'Significant_Damage_And_Serious_Injuries'], dtype=object)

In [23]:
import tensorflow as tf

In [24]:
from keras import Sequential

Using TensorFlow backend.


In [25]:
from keras.layers import Dense

In [26]:
classier = Sequential()

In [27]:
classifier = tf.keras.Sequential([
    tf.keras.layers.Dense(500 , activation = 'relu' , input_dim = 10),
    tf.keras.layers.Dense(300 , activation = 'relu'),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.Dense(50 , activation = 'relu'),
    tf.keras.layers.Dense(4, activation = 'softmax')
])

In [28]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 500)               5500      
_________________________________________________________________
dense_1 (Dense)              (None, 300)               150300    
_________________________________________________________________
dense_2 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 204       
Total params: 191,154
Trainable params: 191,154
Non-trainable params: 0
_________________________________________________________________


In [29]:
classifier.compile(loss = 'sparse_categorical_crossentropy',
                 optimizer = 'adam',
                 metrics = ['accuracy'])

In [30]:
classifier.fit(x_train , y_train, batch_size = 16, epochs = 10 , validation_data = (x_test , y_test))

Train on 8500 samples, validate on 1500 samples
Epoch 1/10
8500/8500 [==============================] - 4s 459us/step - loss: 0.4796 - acc: 0.8189 - val_loss: 0.3301 - val_acc: 0.8913
Epoch 2/10
8500/8500 [==============================] - 3s 390us/step - loss: 0.2525 - acc: 0.9166 - val_loss: 0.2850 - val_acc: 0.9040
Epoch 3/10
8500/8500 [==============================] - 3s 343us/step - loss: 0.2223 - acc: 0.9285 - val_loss: 0.2297 - val_acc: 0.9287
Epoch 4/10
8500/8500 [==============================] - 3s 385us/step - loss: 0.2060 - acc: 0.9300 - val_loss: 0.2074 - val_acc: 0.9300
Epoch 5/10
8500/8500 [==============================] - 3s 343us/step - loss: 0.1973 - acc: 0.9364 - val_loss: 0.2480 - val_acc: 0.9227
Epoch 6/10
8500/8500 [==============================] - 3s 392us/step - loss: 0.1889 - acc: 0.9375 - val_loss: 0.2161 - val_acc: 0.9287
Epoch 7/10
8500/8500 [==============================] - 3s 372us/step - loss: 0.1756 - acc: 0.9405 - val_loss: 0.2132 - val_acc: 0.9253


In [31]:
test_dataset = pd.read_csv('test.csv')

In [32]:
test_dataset.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   4   37949.724386           2                0.069692   
1                   7   30194.805567           2                0.002777   
2                   6   17572.925484           1                0.004316   
3                   3   40209.186341           2                0.199990   
4                   2   35495.525408           2                0.483696   

   Accident_ID  
0            1  
1           10  
2           14  
3           17  
4           21

In [34]:
test_x = test_dataset.drop(['Accident_ID'] , axis = 1)

In [35]:
test_x.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  
0                   4   37949.724386           2                0.069692  
1                   7   30194.805567           2                0.002777  
2                   6   17572.925484           1                0.004316  
3                   3   40209.186341           2                0.199990  
4                   2   35495.525408           2                0.483696

In [36]:
test_x1 = sc_x.transform(test_x)

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  if __name__ == '__main__':


In [39]:
test_x1

array([[-1.39038509,  0.86841631, -0.08055941, ...,  0.63469773,
        -0.01065125, -0.48425896],
       [ 1.01078336,  0.58511028, -0.51140359, ..., -0.1833038 ,
        -0.01065125, -0.6604276 ],
       [-0.53424239,  0.58511028, -0.51140359, ..., -1.51468037,
        -0.97379599, -0.65637586],
       ...,
       [-0.32162417,  0.30180425,  0.49389949, ...,  0.5003538 ,
        -0.01065125, -0.64502209],
       [-0.19688814,  0.01849822,  1.06835839, ..., -0.81444749,
        -0.97379599, -0.65129438],
       [-0.3613129 , -0.54811384, -0.79863304, ...,  0.4206145 ,
        -1.93694072, -0.60347751]])

In [85]:
pred_1 = model.predict(test_x1)

In [86]:
pred_1

array([0, 2, 3, ..., 3, 3, 0])

In [43]:
pred_2 = classifier.predict(test_x1)

In [44]:
pred_2

array([[9.9999607e-01, 2.0420087e-11, 2.4141514e-07, 3.7508235e-06],
       [3.1295059e-08, 4.8239133e-05, 9.9993384e-01, 1.7887758e-05],
       [8.9295017e-06, 2.2448883e-04, 2.8230187e-11, 9.9976653e-01],
       ...,
       [7.0242454e-06, 1.3536399e-05, 8.4589968e-13, 9.9997950e-01],
       [2.3221004e-05, 1.3240447e-05, 5.1159042e-12, 9.9996352e-01],
       [9.9858475e-01, 7.5466232e-07, 1.2869589e-04, 1.2859204e-03]],
      dtype=float32)

In [54]:
contents = []
for x in pred_2:    
    contents.append(x.argmax())

In [82]:
 d = {0 : 'Highly_Fatal_And_Damaging', 1 : 'Minor_Damage_And_Injuries', 2: 'Significant_Damage_And_Fatalities', 3:'Significant_Damage_And_Serious_Injuries'}

In [96]:
final_1 = []
for i in contents:
    final_1.append(d[i])

In [97]:
final_1

['Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Highly_Fat

In [89]:
final_2 = []
for i in pred_1:
    final_2.append(d[i])

In [93]:
final_2

['Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Minor_Damage_And_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities'

In [113]:
output = pd.DataFrame({'Accident_ID': test_dataset.Accident_ID, 'Severity': final_2})
output.to_csv('my_submission.csv', index=False)

In [115]:
output.head()

Accident_ID                                 Severity
0            1                Highly_Fatal_And_Damaging
1           10        Significant_Damage_And_Fatalities
2           14  Significant_Damage_And_Serious_Injuries
3           17  Significant_Damage_And_Serious_Injuries
4           21        Significant_Damage_And_Fatalities

In [118]:
output_1 = pd.DataFrame({'Accident_ID' : test_dataset.Accident_ID, 'Severity' : final_1})
output_1.to_csv('my_submission_1.csv' , index = False)